server:
  port: 8091
spring:
  datasource:
#    url: jdbc:mysql://39.106.186.169:3306/guosim?characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/ckxz?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: "root"
#    username: guosim_prod
    password: "abc123"
#    password: NsznFoG8@#$
    driver-class-name: com.mysql.cj.jdbc.Driver
  #热部署生效
  devtools:
    restart:
      enabled: true
      #设置重启的目录
      additional-paths: src/main/java
mybatis:
  type-aliases-package: com.app.ckxz
  mapperLocations: classpath:mapper/*.xml
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
logging:
  #file: logs/spring-boot-logging.log
  level.com.app.ckxz.userb.mapper: debug
  #config: classpath:logback-spring.xml