package com.app.ckxz.department.moder;

/**
 * 物业部门
 */
public class WuyeDepartment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_department.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_department.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_department.wuye_uuid
     *
     * @mbggenerated
     */
    private String wuyeUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_department.department_name
     *
     * @mbggenerated
     */
    private String departmentName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_department.id
     *
     * @return the value of wuye_department.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_department.id
     *
     * @param id the value for wuye_department.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_department.uuid
     *
     * @return the value of wuye_department.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_department.uuid
     *
     * @param uuid the value for wuye_department.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_department.wuye_uuid
     *
     * @return the value of wuye_department.wuye_uuid
     *
     * @mbggenerated
     */
    public String getWuyeUuid() {
        return wuyeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_department.wuye_uuid
     *
     * @param wuyeUuid the value for wuye_department.wuye_uuid
     *
     * @mbggenerated
     */
    public void setWuyeUuid(String wuyeUuid) {
        this.wuyeUuid = wuyeUuid == null ? null : wuyeUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_department.department_name
     *
     * @return the value of wuye_department.department_name
     *
     * @mbggenerated
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_department.department_name
     *
     * @param departmentName the value for wuye_department.department_name
     *
     * @mbggenerated
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }
}