package com.app.ckxz.company.moder;

import java.util.Date;

public class CompanyEmployee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.company_uuid
     *
     * @mbggenerated
     */
    private String companyUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.user_uuid
     *
     * @mbggenerated
     */
    private String userUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.gender
     *
     * @mbggenerated
     */
    private Boolean gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.education
     *
     * @mbggenerated
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.ismarriage
     *
     * @mbggenerated
     */
    private String ismarriage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.native
     *
     * @mbggenerated
     */
    private String natives;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.isparty
     *
     * @mbggenerated
     */
    private String isparty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.entry_time
     *
     * @mbggenerated
     */
    private Date entryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.quit_time
     *
     * @mbggenerated
     */
    private Date quitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.img_face
     *
     * @mbggenerated
     */
    private String imgFace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.new_img
     *
     * @mbggenerated
     */
    private String newImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.wuye_uuid
     *
     * @mbggenerated
     */
    private String wuyeUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.state
     *
     * @mbggenerated
     */
    private Boolean state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.company
     *
     * @mbggenerated
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.department
     *
     * @mbggenerated
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.program_num
     *
     * @mbggenerated
     */
    private String programNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.URL_address
     *
     * @mbggenerated
     */
    private String urlAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.telephone
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.mobile_phone
     *
     * @mbggenerated
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_employee.is_company_acount
     *
     * @mbggenerated
     */
    private String isCompanyAcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.id
     *
     * @return the value of company_employee.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.id
     *
     * @param id the value for company_employee.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.company_uuid
     *
     * @return the value of company_employee.company_uuid
     *
     * @mbggenerated
     */
    public String getCompanyUuid() {
        return companyUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.company_uuid
     *
     * @param companyUuid the value for company_employee.company_uuid
     *
     * @mbggenerated
     */
    public void setCompanyUuid(String companyUuid) {
        this.companyUuid = companyUuid == null ? null : companyUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.user_uuid
     *
     * @return the value of company_employee.user_uuid
     *
     * @mbggenerated
     */
    public String getUserUuid() {
        return userUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.user_uuid
     *
     * @param userUuid the value for company_employee.user_uuid
     *
     * @mbggenerated
     */
    public void setUserUuid(String userUuid) {
        this.userUuid = userUuid == null ? null : userUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.gender
     *
     * @return the value of company_employee.gender
     *
     * @mbggenerated
     */
    public Boolean getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.gender
     *
     * @param gender the value for company_employee.gender
     *
     * @mbggenerated
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.name
     *
     * @return the value of company_employee.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.name
     *
     * @param name the value for company_employee.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.email
     *
     * @return the value of company_employee.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.email
     *
     * @param email the value for company_employee.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.phone
     *
     * @return the value of company_employee.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.phone
     *
     * @param phone the value for company_employee.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.education
     *
     * @return the value of company_employee.education
     *
     * @mbggenerated
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.education
     *
     * @param education the value for company_employee.education
     *
     * @mbggenerated
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.ismarriage
     *
     * @return the value of company_employee.ismarriage
     *
     * @mbggenerated
     */
    public String getIsmarriage() {
        return ismarriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.ismarriage
     *
     * @param ismarriage the value for company_employee.ismarriage
     *
     * @mbggenerated
     */
    public void setIsmarriage(String ismarriage) {
        this.ismarriage = ismarriage == null ? null : ismarriage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.native
     *
     * @return the value of company_employee.native
     *
     * @mbggenerated
     */
    public String getNative() {
        return natives;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.native
     *
     * @param natives the value for company_employee.native
     *
     * @mbggenerated
     */
    public void setNative(String natives) {
        this.natives = natives == null ? null : natives.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.isparty
     *
     * @return the value of company_employee.isparty
     *
     * @mbggenerated
     */
    public String getIsparty() {
        return isparty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.isparty
     *
     * @param isparty the value for company_employee.isparty
     *
     * @mbggenerated
     */
    public void setIsparty(String isparty) {
        this.isparty = isparty == null ? null : isparty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.entry_time
     *
     * @return the value of company_employee.entry_time
     *
     * @mbggenerated
     */
    public Date getEntryTime() {
        return entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.entry_time
     *
     * @param entryTime the value for company_employee.entry_time
     *
     * @mbggenerated
     */
    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.quit_time
     *
     * @return the value of company_employee.quit_time
     *
     * @mbggenerated
     */
    public Date getQuitTime() {
        return quitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.quit_time
     *
     * @param quitTime the value for company_employee.quit_time
     *
     * @mbggenerated
     */
    public void setQuitTime(Date quitTime) {
        this.quitTime = quitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.add_time
     *
     * @return the value of company_employee.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.add_time
     *
     * @param addTime the value for company_employee.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.img_face
     *
     * @return the value of company_employee.img_face
     *
     * @mbggenerated
     */
    public String getImgFace() {
        return imgFace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.img_face
     *
     * @param imgFace the value for company_employee.img_face
     *
     * @mbggenerated
     */
    public void setImgFace(String imgFace) {
        this.imgFace = imgFace == null ? null : imgFace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.new_img
     *
     * @return the value of company_employee.new_img
     *
     * @mbggenerated
     */
    public String getNewImg() {
        return newImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.new_img
     *
     * @param newImg the value for company_employee.new_img
     *
     * @mbggenerated
     */
    public void setNewImg(String newImg) {
        this.newImg = newImg == null ? null : newImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.wuye_uuid
     *
     * @return the value of company_employee.wuye_uuid
     *
     * @mbggenerated
     */
    public String getWuyeUuid() {
        return wuyeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.wuye_uuid
     *
     * @param wuyeUuid the value for company_employee.wuye_uuid
     *
     * @mbggenerated
     */
    public void setWuyeUuid(String wuyeUuid) {
        this.wuyeUuid = wuyeUuid == null ? null : wuyeUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.state
     *
     * @return the value of company_employee.state
     *
     * @mbggenerated
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.state
     *
     * @param state the value for company_employee.state
     *
     * @mbggenerated
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.company
     *
     * @return the value of company_employee.company
     *
     * @mbggenerated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.company
     *
     * @param company the value for company_employee.company
     *
     * @mbggenerated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.department
     *
     * @return the value of company_employee.department
     *
     * @mbggenerated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.department
     *
     * @param department the value for company_employee.department
     *
     * @mbggenerated
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.position
     *
     * @return the value of company_employee.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.position
     *
     * @param position the value for company_employee.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.program_num
     *
     * @return the value of company_employee.program_num
     *
     * @mbggenerated
     */
    public String getProgramNum() {
        return programNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.program_num
     *
     * @param programNum the value for company_employee.program_num
     *
     * @mbggenerated
     */
    public void setProgramNum(String programNum) {
        this.programNum = programNum == null ? null : programNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.URL_address
     *
     * @return the value of company_employee.URL_address
     *
     * @mbggenerated
     */
    public String getUrlAddress() {
        return urlAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.URL_address
     *
     * @param urlAddress the value for company_employee.URL_address
     *
     * @mbggenerated
     */
    public void setUrlAddress(String urlAddress) {
        this.urlAddress = urlAddress == null ? null : urlAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.address
     *
     * @return the value of company_employee.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.address
     *
     * @param address the value for company_employee.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.telephone
     *
     * @return the value of company_employee.telephone
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.telephone
     *
     * @param telephone the value for company_employee.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.mobile_phone
     *
     * @return the value of company_employee.mobile_phone
     *
     * @mbggenerated
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.mobile_phone
     *
     * @param mobilePhone the value for company_employee.mobile_phone
     *
     * @mbggenerated
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_employee.is_company_acount
     *
     * @return the value of company_employee.is_company_acount
     *
     * @mbggenerated
     */
    public String getIsCompanyAcount() {
        return isCompanyAcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_employee.is_company_acount
     *
     * @param isCompanyAcount the value for company_employee.is_company_acount
     *
     * @mbggenerated
     */
    public void setIsCompanyAcount(String isCompanyAcount) {
        this.isCompanyAcount = isCompanyAcount == null ? null : isCompanyAcount.trim();
    }
}