package com.app.ckxz.company.moder;

import java.util.Date;

public class Company {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.occupancy_time
     *
     * @mbggenerated
     */
    private Date occupancyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.wuye_uuid
     *
     * @mbggenerated
     */
    private String wuyeUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.user_admin_uuid
     *
     * @mbggenerated
     */
    private String userAdminUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.dock_pkid
     *
     * @mbggenerated
     */
    private String dockPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.program_num
     *
     * @mbggenerated
     */
    private String programNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.website
     *
     * @mbggenerated
     */
    private String website;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.introduction
     *
     * @mbggenerated
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.id
     *
     * @return the value of company.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.id
     *
     * @param id the value for company.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.name
     *
     * @return the value of company.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.name
     *
     * @param name the value for company.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.uuid
     *
     * @return the value of company.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.uuid
     *
     * @param uuid the value for company.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.occupancy_time
     *
     * @return the value of company.occupancy_time
     *
     * @mbggenerated
     */
    public Date getOccupancyTime() {
        return occupancyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.occupancy_time
     *
     * @param occupancyTime the value for company.occupancy_time
     *
     * @mbggenerated
     */
    public void setOccupancyTime(Date occupancyTime) {
        this.occupancyTime = occupancyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.created_time
     *
     * @return the value of company.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.created_time
     *
     * @param createdTime the value for company.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.state
     *
     * @return the value of company.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.state
     *
     * @param state the value for company.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.wuye_uuid
     *
     * @return the value of company.wuye_uuid
     *
     * @mbggenerated
     */
    public String getWuyeUuid() {
        return wuyeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.wuye_uuid
     *
     * @param wuyeUuid the value for company.wuye_uuid
     *
     * @mbggenerated
     */
    public void setWuyeUuid(String wuyeUuid) {
        this.wuyeUuid = wuyeUuid == null ? null : wuyeUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.user_admin_uuid
     *
     * @return the value of company.user_admin_uuid
     *
     * @mbggenerated
     */
    public String getUserAdminUuid() {
        return userAdminUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.user_admin_uuid
     *
     * @param userAdminUuid the value for company.user_admin_uuid
     *
     * @mbggenerated
     */
    public void setUserAdminUuid(String userAdminUuid) {
        this.userAdminUuid = userAdminUuid == null ? null : userAdminUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.dock_pkid
     *
     * @return the value of company.dock_pkid
     *
     * @mbggenerated
     */
    public String getDockPkid() {
        return dockPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.dock_pkid
     *
     * @param dockPkid the value for company.dock_pkid
     *
     * @mbggenerated
     */
    public void setDockPkid(String dockPkid) {
        this.dockPkid = dockPkid == null ? null : dockPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.program_num
     *
     * @return the value of company.program_num
     *
     * @mbggenerated
     */
    public String getProgramNum() {
        return programNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.program_num
     *
     * @param programNum the value for company.program_num
     *
     * @mbggenerated
     */
    public void setProgramNum(String programNum) {
        this.programNum = programNum == null ? null : programNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.address
     *
     * @return the value of company.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.address
     *
     * @param address the value for company.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.phone
     *
     * @return the value of company.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.phone
     *
     * @param phone the value for company.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.website
     *
     * @return the value of company.website
     *
     * @mbggenerated
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.website
     *
     * @param website the value for company.website
     *
     * @mbggenerated
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.introduction
     *
     * @return the value of company.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.introduction
     *
     * @param introduction the value for company.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.note
     *
     * @return the value of company.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.note
     *
     * @param note the value for company.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}