package com.app.ckxz.company.mapper;

import com.app.ckxz.company.moder.CompanyEmployee;
import java.util.List;
import java.util.Map;

public interface CompanyEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_employee
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    int deleteByListId(List<String> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_employee
     *
     * @mbggenerated
     */
    int insert(CompanyEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_employee
     *
     * @mbggenerated
     */
    CompanyEmployee selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_employee
     *
     * @mbggenerated
     */
    List<CompanyEmployee> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_employee
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CompanyEmployee record);

    /**
     *查询所有企业管理人
     * @return
     */
    List<CompanyEmployee> isCompanyEmployeeAcount();
}