package com.app.ckxz.wuyeemployee.moder;

import java.util.Date;

public class WuyeEmployee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_employee.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_employee.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_employee.employee_name
     *
     * @mbggenerated
     */
    private String employeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_employee.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_employee.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_employee.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_employee.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_employee.createor
     *
     * @mbggenerated
     */
    private String createor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_employee.created_date
     *
     * @mbggenerated
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_employee.quit_date
     *
     * @mbggenerated
     */
    private Date quitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_employee.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_employee.department_uuid
     *
     * @mbggenerated
     */
    private String departmentUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_employee.wuye_uuid
     *
     * @mbggenerated
     */
    private String wuyeUuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_employee.id
     *
     * @return the value of wuye_employee.id
     *
     * @mbggenerated
     */
    /**
     * 角色
     */
    private String roleName;
    /**
     * 部门
     */
    private String departmentName;
    /**
     * 登录账户
     */
    private String realEmail;
    public Long getId() {
        return id;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getDepartmentName() {
        return departmentName;
    }

    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    public String getRealEmail() {
        return realEmail;
    }

    public void setRealEmail(String realEmail) {
        this.realEmail = realEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_employee.id
     *
     * @param id the value for wuye_employee.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_employee.uuid
     *
     * @return the value of wuye_employee.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_employee.uuid
     *
     * @param uuid the value for wuye_employee.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_employee.employee_name
     *
     * @return the value of wuye_employee.employee_name
     *
     * @mbggenerated
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_employee.employee_name
     *
     * @param employeeName the value for wuye_employee.employee_name
     *
     * @mbggenerated
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_employee.user_id
     *
     * @return the value of wuye_employee.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_employee.user_id
     *
     * @param userId the value for wuye_employee.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_employee.phone
     *
     * @return the value of wuye_employee.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_employee.phone
     *
     * @param phone the value for wuye_employee.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_employee.email
     *
     * @return the value of wuye_employee.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_employee.email
     *
     * @param email the value for wuye_employee.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_employee.state
     *
     * @return the value of wuye_employee.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_employee.state
     *
     * @param state the value for wuye_employee.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_employee.createor
     *
     * @return the value of wuye_employee.createor
     *
     * @mbggenerated
     */
    public String getCreateor() {
        return createor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_employee.createor
     *
     * @param createor the value for wuye_employee.createor
     *
     * @mbggenerated
     */
    public void setCreateor(String createor) {
        this.createor = createor == null ? null : createor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_employee.created_date
     *
     * @return the value of wuye_employee.created_date
     *
     * @mbggenerated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_employee.created_date
     *
     * @param createdDate the value for wuye_employee.created_date
     *
     * @mbggenerated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_employee.quit_date
     *
     * @return the value of wuye_employee.quit_date
     *
     * @mbggenerated
     */
    public Date getQuitDate() {
        return quitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_employee.quit_date
     *
     * @param quitDate the value for wuye_employee.quit_date
     *
     * @mbggenerated
     */
    public void setQuitDate(Date quitDate) {
        this.quitDate = quitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_employee.note
     *
     * @return the value of wuye_employee.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_employee.note
     *
     * @param note the value for wuye_employee.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_employee.department_uuid
     *
     * @return the value of wuye_employee.department_uuid
     *
     * @mbggenerated
     */
    public String getDepartmentUuid() {
        return departmentUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_employee.department_uuid
     *
     * @param departmentUuid the value for wuye_employee.department_uuid
     *
     * @mbggenerated
     */
    public void setDepartmentUuid(String departmentUuid) {
        this.departmentUuid = departmentUuid == null ? null : departmentUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_employee.wuye_uuid
     *
     * @return the value of wuye_employee.wuye_uuid
     *
     * @mbggenerated
     */
    public String getWuyeUuid() {
        return wuyeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_employee.wuye_uuid
     *
     * @param wuyeUuid the value for wuye_employee.wuye_uuid
     *
     * @mbggenerated
     */
    public void setWuyeUuid(String wuyeUuid) {
        this.wuyeUuid = wuyeUuid == null ? null : wuyeUuid.trim();
    }
}