package com.app.ckxz.wuyeroles.mapper;

import com.app.ckxz.wuyeroles.moder.wuyeRolePersonnel;
import java.util.List;

public interface wuyeRolePersonnelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuye_role_personnel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuye_role_personnel
     *
     * @mbggenerated
     */
    int insert(wuyeRolePersonnel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuye_role_personnel
     *
     * @mbggenerated
     */
    wuyeRolePersonnel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuye_role_personnel
     *
     * @mbggenerated
     */
    List<wuyeRolePersonnel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuye_role_personnel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(wuyeRolePersonnel record);
}