package com.app.ckxz.wuyeroles.mapper;

import com.app.ckxz.wuyeroles.moder.WuyeRoles;
import java.util.List;

public interface WuyeRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuye_roles
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuye_roles
     *
     * @mbggenerated
     */
    int insert(WuyeRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuye_roles
     *
     * @mbggenerated
     */
    WuyeRoles selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuye_roles
     *
     * @mbggenerated
     */
    List<WuyeRoles> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuye_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WuyeRoles record);
}