package com.app.ckxz.userb.moder;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class UserD {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.user_img
     *
     * @mbggenerated
     */
    private String userImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.phone_info
     *
     * @mbggenerated
     */
    private String phoneInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.connect_mode
     *
     * @mbggenerated
     */
    private Integer connectMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.app_id
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.card_id
     *
     * @mbggenerated
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.wechat_openid
     *
     * @mbggenerated
     */
    private String wechatOpenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.wechat_unionid
     *
     * @mbggenerated
     */
    private String wechatUnionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.app_version
     *
     * @mbggenerated
     */
    private String appVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.last_login_time
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.last_active_time
     *
     * @mbggenerated
     */
    private Date lastActiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.is_master
     *
     * @mbggenerated
     */
    private Integer isMaster;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.introduce
     *
     * @mbggenerated
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.wx_profile
     *
     * @mbggenerated
     */
    private String wxProfile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.dock_pkid
     *
     * @mbggenerated
     */
    private String dockPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.dock_pkid2
     *
     * @mbggenerated
     */
    private String dockPkid2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.room_number
     *
     * @mbggenerated
     */
    private String roomNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.home_address
     *
     * @mbggenerated
     */
    private String homeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.age
     *
     * @mbggenerated
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.domicile_place
     *
     * @mbggenerated
     */
    private String domicilePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.card_id_img
     *
     * @mbggenerated
     */
    private String cardIdImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.card_id_num
     *
     * @mbggenerated
     */
    private String cardIdNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.email
     *
     * @mbggenerated
     */
    private String email;
    private String profileImgString;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.face_photo
     *
     * @mbggenerated
     */
    private String facePhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.face_add_time
     *
     * @mbggenerated
     */
    private Date faceAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.bankcard_no
     *
     * @mbggenerated
     */
    private String bankcardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.is_certification
     *
     * @mbggenerated
     */
    private String isCertification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.ca_valid_date
     *
     * @mbggenerated
     */
    private Date caValidDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.login_id
     *
     * @mbggenerated
     */
    private String loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_d.profile_img
     *
     * @mbggenerated
     */
    private String profileImg;
    /**
     * 物业的uuid
     */
    private String wuyeUuid;

    public String getProfileImgString() {
        return profileImgString;
    }

    public void setProfileImgString(String profileImgString) {
        this.profileImgString = profileImgString;
    }

    public String getWuyeUuid() {
        return wuyeUuid;
    }

    public void setWuyeUuid(String wuyeUuid) {
        this.wuyeUuid = wuyeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.id
     *
     * @return the value of user_d.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.id
     *
     * @param id the value for user_d.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.uuid
     *
     * @return the value of user_d.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.uuid
     *
     * @param uuid the value for user_d.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.user_img
     *
     * @return the value of user_d.user_img
     *
     * @mbggenerated
     */
    public String getUserImg() {
        return userImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.user_img
     *
     * @param userImg the value for user_d.user_img
     *
     * @mbggenerated
     */
    public void setUserImg(String userImg) {
        this.userImg = userImg == null ? null : userImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.user_id
     *
     * @return the value of user_d.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.user_id
     *
     * @param userId the value for user_d.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.password
     *
     * @return the value of user_d.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.password
     *
     * @param password the value for user_d.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.nickname
     *
     * @return the value of user_d.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.nickname
     *
     * @param nickname the value for user_d.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.phone_info
     *
     * @return the value of user_d.phone_info
     *
     * @mbggenerated
     */
    public String getPhoneInfo() {
        return phoneInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.phone_info
     *
     * @param phoneInfo the value for user_d.phone_info
     *
     * @mbggenerated
     */
    public void setPhoneInfo(String phoneInfo) {
        this.phoneInfo = phoneInfo == null ? null : phoneInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.connect_mode
     *
     * @return the value of user_d.connect_mode
     *
     * @mbggenerated
     */
    public Integer getConnectMode() {
        return connectMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.connect_mode
     *
     * @param connectMode the value for user_d.connect_mode
     *
     * @mbggenerated
     */
    public void setConnectMode(Integer connectMode) {
        this.connectMode = connectMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.app_id
     *
     * @return the value of user_d.app_id
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.app_id
     *
     * @param appId the value for user_d.app_id
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.created_time
     *
     * @return the value of user_d.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.created_time
     *
     * @param createdTime the value for user_d.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.card_id
     *
     * @return the value of user_d.card_id
     *
     * @mbggenerated
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.card_id
     *
     * @param cardId the value for user_d.card_id
     *
     * @mbggenerated
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.wechat_openid
     *
     * @return the value of user_d.wechat_openid
     *
     * @mbggenerated
     */
    public String getWechatOpenid() {
        return wechatOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.wechat_openid
     *
     * @param wechatOpenid the value for user_d.wechat_openid
     *
     * @mbggenerated
     */
    public void setWechatOpenid(String wechatOpenid) {
        this.wechatOpenid = wechatOpenid == null ? null : wechatOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.wechat_unionid
     *
     * @return the value of user_d.wechat_unionid
     *
     * @mbggenerated
     */
    public String getWechatUnionid() {
        return wechatUnionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.wechat_unionid
     *
     * @param wechatUnionid the value for user_d.wechat_unionid
     *
     * @mbggenerated
     */
    public void setWechatUnionid(String wechatUnionid) {
        this.wechatUnionid = wechatUnionid == null ? null : wechatUnionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.app_version
     *
     * @return the value of user_d.app_version
     *
     * @mbggenerated
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.app_version
     *
     * @param appVersion the value for user_d.app_version
     *
     * @mbggenerated
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion == null ? null : appVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.last_login_time
     *
     * @return the value of user_d.last_login_time
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.last_login_time
     *
     * @param lastLoginTime the value for user_d.last_login_time
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.last_active_time
     *
     * @return the value of user_d.last_active_time
     *
     * @mbggenerated
     */
    public Date getLastActiveTime() {
        return lastActiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.last_active_time
     *
     * @param lastActiveTime the value for user_d.last_active_time
     *
     * @mbggenerated
     */
    public void setLastActiveTime(Date lastActiveTime) {
        this.lastActiveTime = lastActiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.is_master
     *
     * @return the value of user_d.is_master
     *
     * @mbggenerated
     */
    public Integer getIsMaster() {
        return isMaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.is_master
     *
     * @param isMaster the value for user_d.is_master
     *
     * @mbggenerated
     */
    public void setIsMaster(Integer isMaster) {
        this.isMaster = isMaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.real_name
     *
     * @return the value of user_d.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.real_name
     *
     * @param realName the value for user_d.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.birthday
     *
     * @return the value of user_d.birthday
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "YYYY-MM-dd")
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.birthday
     *
     * @param birthday the value for user_d.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.introduce
     *
     * @return the value of user_d.introduce
     *
     * @mbggenerated
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.introduce
     *
     * @param introduce the value for user_d.introduce
     *
     * @mbggenerated
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.address
     *
     * @return the value of user_d.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.address
     *
     * @param address the value for user_d.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.sex
     *
     * @return the value of user_d.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.sex
     *
     * @param sex the value for user_d.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.wx_profile
     *
     * @return the value of user_d.wx_profile
     *
     * @mbggenerated
     */
    public String getWxProfile() {
        return wxProfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.wx_profile
     *
     * @param wxProfile the value for user_d.wx_profile
     *
     * @mbggenerated
     */
    public void setWxProfile(String wxProfile) {
        this.wxProfile = wxProfile == null ? null : wxProfile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.dock_pkid
     *
     * @return the value of user_d.dock_pkid
     *
     * @mbggenerated
     */
    public String getDockPkid() {
        return dockPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.dock_pkid
     *
     * @param dockPkid the value for user_d.dock_pkid
     *
     * @mbggenerated
     */
    public void setDockPkid(String dockPkid) {
        this.dockPkid = dockPkid == null ? null : dockPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.dock_pkid2
     *
     * @return the value of user_d.dock_pkid2
     *
     * @mbggenerated
     */
    public String getDockPkid2() {
        return dockPkid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.dock_pkid2
     *
     * @param dockPkid2 the value for user_d.dock_pkid2
     *
     * @mbggenerated
     */
    public void setDockPkid2(String dockPkid2) {
        this.dockPkid2 = dockPkid2 == null ? null : dockPkid2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.room_number
     *
     * @return the value of user_d.room_number
     *
     * @mbggenerated
     */
    public String getRoomNumber() {
        return roomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.room_number
     *
     * @param roomNumber the value for user_d.room_number
     *
     * @mbggenerated
     */
    public void setRoomNumber(String roomNumber) {
        this.roomNumber = roomNumber == null ? null : roomNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.home_address
     *
     * @return the value of user_d.home_address
     *
     * @mbggenerated
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.home_address
     *
     * @param homeAddress the value for user_d.home_address
     *
     * @mbggenerated
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress == null ? null : homeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.age
     *
     * @return the value of user_d.age
     *
     * @mbggenerated
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.age
     *
     * @param age the value for user_d.age
     *
     * @mbggenerated
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.domicile_place
     *
     * @return the value of user_d.domicile_place
     *
     * @mbggenerated
     */
    public String getDomicilePlace() {
        return domicilePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.domicile_place
     *
     * @param domicilePlace the value for user_d.domicile_place
     *
     * @mbggenerated
     */
    public void setDomicilePlace(String domicilePlace) {
        this.domicilePlace = domicilePlace == null ? null : domicilePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.card_id_img
     *
     * @return the value of user_d.card_id_img
     *
     * @mbggenerated
     */
    public String getCardIdImg() {
        return cardIdImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.card_id_img
     *
     * @param cardIdImg the value for user_d.card_id_img
     *
     * @mbggenerated
     */
    public void setCardIdImg(String cardIdImg) {
        this.cardIdImg = cardIdImg == null ? null : cardIdImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.card_id_num
     *
     * @return the value of user_d.card_id_num
     *
     * @mbggenerated
     */
    public String getCardIdNum() {
        return cardIdNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.card_id_num
     *
     * @param cardIdNum the value for user_d.card_id_num
     *
     * @mbggenerated
     */
    public void setCardIdNum(String cardIdNum) {
        this.cardIdNum = cardIdNum == null ? null : cardIdNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.email
     *
     * @return the value of user_d.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.email
     *
     * @param email the value for user_d.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.face_photo
     *
     * @return the value of user_d.face_photo
     *
     * @mbggenerated
     */
    public String getFacePhoto() {
        return facePhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.face_photo
     *
     * @param facePhoto the value for user_d.face_photo
     *
     * @mbggenerated
     */
    public void setFacePhoto(String facePhoto) {
        this.facePhoto = facePhoto == null ? null : facePhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.face_add_time
     *
     * @return the value of user_d.face_add_time
     *
     * @mbggenerated
     */
    public Date getFaceAddTime() {
        return faceAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.face_add_time
     *
     * @param faceAddTime the value for user_d.face_add_time
     *
     * @mbggenerated
     */
    public void setFaceAddTime(Date faceAddTime) {
        this.faceAddTime = faceAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.bankcard_no
     *
     * @return the value of user_d.bankcard_no
     *
     * @mbggenerated
     */
    public String getBankcardNo() {
        return bankcardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.bankcard_no
     *
     * @param bankcardNo the value for user_d.bankcard_no
     *
     * @mbggenerated
     */
    public void setBankcardNo(String bankcardNo) {
        this.bankcardNo = bankcardNo == null ? null : bankcardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.is_certification
     *
     * @return the value of user_d.is_certification
     *
     * @mbggenerated
     */
    public String getIsCertification() {
        return isCertification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.is_certification
     *
     * @param isCertification the value for user_d.is_certification
     *
     * @mbggenerated
     */
    public void setIsCertification(String isCertification) {
        this.isCertification = isCertification == null ? null : isCertification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.ca_valid_date
     *
     * @return the value of user_d.ca_valid_date
     *
     * @mbggenerated
     */
    public Date getCaValidDate() {
        return caValidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.ca_valid_date
     *
     * @param caValidDate the value for user_d.ca_valid_date
     *
     * @mbggenerated
     */
    public void setCaValidDate(Date caValidDate) {
        this.caValidDate = caValidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.login_id
     *
     * @return the value of user_d.login_id
     *
     * @mbggenerated
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.login_id
     *
     * @param loginId the value for user_d.login_id
     *
     * @mbggenerated
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId == null ? null : loginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_d.profile_img
     *
     * @return the value of user_d.profile_img
     *
     * @mbggenerated
     */
    public String getProfileImg() {
        return profileImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_d.profile_img
     *
     * @param profileImg the value for user_d.profile_img
     *
     * @mbggenerated
     */
    public void setProfileImg(String profileImg) {
        this.profileImg = profileImg == null ? null : profileImg.trim();
    }
}