package com.app.ckxz.wuyeemployee.mapper;

import com.app.ckxz.base.mapper.BaseMapper;
import com.app.ckxz.department.moder.WuyeDepartment;
import com.app.ckxz.wuyeemployee.moder.WuyeEmployee;
import java.util.List;
import java.util.Map;

public interface WuyeEmployeeMapper extends BaseMapper<WuyeEmployee,String> {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuye_employee
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuye_employee
     *
     * @mbggenerated
     */
    int insert(WuyeEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuye_employee
     *
     * @mbggenerated
     */
    WuyeEmployee selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuye_employee
     *
     * @mbggenerated
     */
    List<WuyeEmployee> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuye_employee
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WuyeEmployee record);

    List<WuyeEmployee> selectWuyeEmployeeCondition(Map<String,Object> map);
}