package com.app.ckxz.wuyeroles.moder;

public class WuyeRoles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_roles.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_roles.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_roles.wuye_uuid
     *
     * @mbggenerated
     */
    private String wuyeUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_roles.wuye_id
     *
     * @mbggenerated
     */
    private String wuyeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_roles.role_key
     *
     * @mbggenerated
     */
    private String roleKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_roles.role_value
     *
     * @mbggenerated
     */
    private String roleValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_roles.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_roles.id
     *
     * @return the value of wuye_roles.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_roles.id
     *
     * @param id the value for wuye_roles.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_roles.uuid
     *
     * @return the value of wuye_roles.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_roles.uuid
     *
     * @param uuid the value for wuye_roles.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_roles.wuye_uuid
     *
     * @return the value of wuye_roles.wuye_uuid
     *
     * @mbggenerated
     */
    public String getWuyeUuid() {
        return wuyeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_roles.wuye_uuid
     *
     * @param wuyeUuid the value for wuye_roles.wuye_uuid
     *
     * @mbggenerated
     */
    public void setWuyeUuid(String wuyeUuid) {
        this.wuyeUuid = wuyeUuid == null ? null : wuyeUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_roles.wuye_id
     *
     * @return the value of wuye_roles.wuye_id
     *
     * @mbggenerated
     */
    public String getWuyeId() {
        return wuyeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_roles.wuye_id
     *
     * @param wuyeId the value for wuye_roles.wuye_id
     *
     * @mbggenerated
     */
    public void setWuyeId(String wuyeId) {
        this.wuyeId = wuyeId == null ? null : wuyeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_roles.role_key
     *
     * @return the value of wuye_roles.role_key
     *
     * @mbggenerated
     */
    public String getRoleKey() {
        return roleKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_roles.role_key
     *
     * @param roleKey the value for wuye_roles.role_key
     *
     * @mbggenerated
     */
    public void setRoleKey(String roleKey) {
        this.roleKey = roleKey == null ? null : roleKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_roles.role_value
     *
     * @return the value of wuye_roles.role_value
     *
     * @mbggenerated
     */
    public String getRoleValue() {
        return roleValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_roles.role_value
     *
     * @param roleValue the value for wuye_roles.role_value
     *
     * @mbggenerated
     */
    public void setRoleValue(String roleValue) {
        this.roleValue = roleValue == null ? null : roleValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_roles.note
     *
     * @return the value of wuye_roles.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_roles.note
     *
     * @param note the value for wuye_roles.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}