package com.app.ckxz.wuyeroles.moder;

public class wuyeRolePersonnel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_role_personnel.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_role_personnel.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_role_personnel.role_uuid
     *
     * @mbggenerated
     */
    private String roleUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuye_role_personnel.employee_uuid
     *
     * @mbggenerated
     */
    private String employeeUuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_role_personnel.id
     *
     * @return the value of wuye_role_personnel.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_role_personnel.id
     *
     * @param id the value for wuye_role_personnel.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_role_personnel.uuid
     *
     * @return the value of wuye_role_personnel.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_role_personnel.uuid
     *
     * @param uuid the value for wuye_role_personnel.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_role_personnel.role_uuid
     *
     * @return the value of wuye_role_personnel.role_uuid
     *
     * @mbggenerated
     */
    public String getRoleUuid() {
        return roleUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_role_personnel.role_uuid
     *
     * @param roleUuid the value for wuye_role_personnel.role_uuid
     *
     * @mbggenerated
     */
    public void setRoleUuid(String roleUuid) {
        this.roleUuid = roleUuid == null ? null : roleUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuye_role_personnel.employee_uuid
     *
     * @return the value of wuye_role_personnel.employee_uuid
     *
     * @mbggenerated
     */
    public String getEmployeeUuid() {
        return employeeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuye_role_personnel.employee_uuid
     *
     * @param employeeUuid the value for wuye_role_personnel.employee_uuid
     *
     * @mbggenerated
     */
    public void setEmployeeUuid(String employeeUuid) {
        this.employeeUuid = employeeUuid == null ? null : employeeUuid.trim();
    }
}